name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    # keep your safeguard (prevents bot loops)
    if: github.actor != 'github-actions[bot]'
    steps:
      # 1) TAG/RELEASE any merged release PRs (creates vX.Y.Z and GitHub Release)
      - uses: googleapis/release-please-action@v4
        id: tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-pull-request: true

      # 2) OPEN/REFRESH the next release PR (no tag here)
      - uses: googleapis/release-please-action@v4
        id: pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-release: true

      # -------- publish only when a release was created in step 1 --------
      - uses: actions/checkout@v4
        if: ${{ steps.tag.outputs.release_created }}
        with:
          ref: ${{ steps.tag.outputs.tag_name }}
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@v4
        if: ${{ steps.tag.outputs.release_created }}
        with:
          version: 8.15.0
          run_install: false

      - uses: actions/setup-node@v4
        if: ${{ steps.tag.outputs.release_created }}
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Configure npm auth
        if: ${{ steps.tag.outputs.release_created }}
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        if: ${{ steps.tag.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.tag.outputs.release_created }}
        run: pnpm build

      - name: Publish to npm
        if: ${{ steps.tag.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish -r --access public --no-git-checks
