name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: release-please
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Only run publish steps when a release was actually created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: ${{ steps.release.outputs.tag_name }}
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          version: 8.15.0

      # Ensure pnpm sees the token (belt-and-suspenders)
      - name: Configure npm auth
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --no-git-checks --access public # drop --access if not scoped
          # add --provenance if you want npm provenance
